export let doctorWho = [
    'Doctor Who',
    'David Tennant',
    'Matt Smith',
    'TARDIS',
    'Daleks',
    'Cybermen',
    'The Master',
    'Companion',
    'Gallifrey',
    'Time Lord',
    // 'The Doctor',
    // 'William Hartnell',
    // 'Patrick Troughton',
    // 'Jon Pertwee',
    // 'Tom Baker',
    // 'Peter Davison',
    // 'Colin Baker',
    // 'Sylvester McCoy',
    // 'Paul McGann',
    // 'Christopher Eccleston',
    // 'Peter Capaldi',
    // 'Jodie Whittaker',
    // 'Rose Tyler',
    // 'Billie Piper',
    // 'Martha Jones',
    // 'Freema Agyeman',
    // 'Donna Noble',
    // 'Catherine Tate',
    // 'Mickey Smith',
    // 'Noel Clarke',
    // 'Jack Harkness',
    // 'John Barrowman',
    // 'Amy Pond',
    // 'Karen Gillan',
    // 'Rory William',
    // 'Arthur Darvill',
    // 'River Song',
    // 'Alex Kingston',
    // 'Clara Oswold',
    // 'Jenna Coleman',
    // 'Bill Potts',
    // 'Pearl Mackie',
    // 'Macra',
    // 'Sontarans',
    // 'Davros',
    // 'Rassilon',
    // 'Silurians',
    // 'Great Intelligence',
    // 'Ice Warriors',
    // 'Zygons',
    // 'Slitheen',
    // 'Ood',
    // 'Judoon',
    // 'Weeping Angels',
    // 'The Silence',
    // 'Ogrons',
    // 'Rani',
    // 'Black Guardian',
]
