export let harryPotter = [
    'Harry Potter',
    'Sirius Black',
    'Albus Dumbledore',
    'J. K. Rowling',
    'Wizard',
    'Hermione Granger',
    'Ron Weasley',
    'Hogwarts',
    'Lord Voldemort',
    'Ministry of Magic',
    'Muggles',
    'Rubeus Hagrid',
    'Severus Snape',
    'Draco Malfoy',
    'Quirinus Quirrell',
    "Philospher's Stone",
    'Ginny Weasley',
    'Basilisk',
    'Gilderoy Lockhart',
    'Parsleytongue',
    'Dark Arts',
    'Remus Lupin',
    'Werewolf',
    'Peter Pettigrew',
    'Alastor "Mad-Eye" Moody',
    'Barty Crouch, Jr',
    'Cedric Diggory',
    'Order of the Phoenix',
    'Dolores Umbridge',
    "Dumbledore's Army",
    'Cho Chang',
    'Ministry of Magic',
    'Lavender Brown',
    'Horace Slughorn',
    'Pensieve',
    'Horcruxes',
]